# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Release

on:
  create:
    tags:
    - '*.*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 11
      
      - name: Set RELEASE_VERSION
        run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}
  
      - run: npm install vsce -g
      - run: npm install gulp
      - run: npm install
      
      - name: set version
        run: sed -i 's/1.2007.1/'"$RELEASE_VERSION"'/g' ./src/helpers/constants.t
      
      - run: gulp test
      - run: gulp package

